# src/config.py
import os
from pathlib import Path
from typing import Dict

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = os.path.join(PROJECT_ROOT, "data", "raw")
PROCESSED_DATA_DIR = os.path.join(PROJECT_ROOT, "data", "processed")

# List of features to be used for model training and prediction
FEATURES = [
    "ma7",
    "ma21",
    "sma200",
    "rsi",
    "macd",
    "bollinger_upper",
    "bollinger_lower",
    "stochastic_oscillator",
    "atr",
    "return_1d",
    "return_5d",
    "return_21d",
    "volatility_21d",
    "price_to_sma200",
    "rsi_slope",
    "ma_spread",
    "volume_ratio",
    "atr_ratio",
    "vix_close",
    "vix_ma5",
    "vix_change_1d",
    "mean_sentiment_score",
    "positive",
    "negative",
    "neutral",
]

# Hyperparameters for the XGBoost Classifier (regularized for low-noise time series)
XGB_MODEL_PARAMS = {
    "n_estimators": 150,
    "learning_rate": 0.03,
    "max_depth": 3,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "reg_alpha": 0.1,
    "reg_lambda": 1.0,
    "random_state": 42,
    "eval_metric": "logloss",
}

# S&P 100 Corporate Company Names Mapping
COMPANY_NAMES: Dict[str, str] = {
    # 1. Information Technology & AI Semiconductors
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "NVDA": "NVIDIA Corporation",
    "AVGO": "Broadcom Inc.",
    "ORCL": "Oracle Corporation",
    "CRM": "Salesforce, Inc.",
    "AMD": "Advanced Micro Devices, Inc.",
    "ADBE": "Adobe Inc.",
    "QCOM": "QUALCOMM Incorporated",
    "TXN": "Texas Instruments Incorporated",
    "INTC": "Intel Corporation",
    "IBM": "International Business Machines Corp.",
    "AMAT": "Applied Materials, Inc.",
    "NOW": "ServiceNow, Inc.",
    "LRCX": "Lam Research Corporation",
    "MU": "Micron Technology, Inc.",
    "PANW": "Palo Alto Networks, Inc.",
    "ADI": "Analog Devices, Inc.",
    "KLAC": "KLA Corporation",
    "SNPS": "Synopsys, Inc.",
    "CDNS": "Cadence Design Systems, Inc.",
    "CRWD": "CrowdStrike Holdings, Inc.",
    "PLTR": "Palantir Technologies Inc.",
    "TSM": "Taiwan Semiconductor Mfg. Co.",
    "ASML": "ASML Holding N.V.",
    # 2. Communication Services & Digital Media
    "GOOGL": "Alphabet Inc.",
    "META": "Meta Platforms, Inc.",
    "NFLX": "Netflix, Inc.",
    "DIS": "The Walt Disney Company",
    "CMCSA": "Comcast Corporation",
    # 3. Consumer Discretionary & E-Commerce
    "AMZN": "Amazon.com, Inc.",
    "TSLA": "Tesla, Inc.",
    "HD": "The Home Depot, Inc.",
    "MCD": "McDonald's Corporation",
    "NKE": "NIKE, Inc.",
    "LOW": "Lowe's Companies, Inc.",
    "BKNG": "Booking Holdings Inc.",
    "SBUX": "Starbucks Corporation",
    "TJX": "The TJX Companies, Inc.",
    "TGT": "Target Corporation",
    "F": "Ford Motor Company",
    # 4. Consumer Staples & Retail Anchors
    "COST": "Costco Wholesale Corporation",
    "WMT": "Walmart Inc.",
    "PG": "The Procter & Gamble Company",
    "KO": "The Coca-Cola Company",
    "PEP": "PepsiCo, Inc.",
    "PM": "Philip Morris International Inc.",
    "MDLZ": "Mondelez International, Inc.",
    "MO": "Altria Group, Inc.",
    "CL": "Colgate-Palmolive Company",
    "KMB": "Kimberly-Clark Corporation",
    # 5. Financials, Banking & Payment Networks
    "JPM": "JPMorgan Chase & Co.",
    "V": "Visa Inc.",
    "MA": "Mastercard Incorporated",
    "BAC": "Bank of America Corporation",
    "WFC": "Wells Fargo & Company",
    "MS": "Morgan Stanley",
    "GS": "The Goldman Sachs Group, Inc.",
    "BLK": "BlackRock, Inc.",
    "SPGI": "S&P Global Inc.",
    "AXP": "American Express Company",
    "C": "Citigroup Inc.",
    "SCHW": "The Charles Schwab Corporation",
    "PGR": "The Progressive Corporation",
    "CB": "Chubb Limited",
    # 6. Healthcare, Biotech & Medical Devices
    "LLY": "Eli Lilly and Company",
    "UNH": "UnitedHealth Group Incorporated",
    "JNJ": "Johnson & Johnson",
    "ABBV": "AbbVie Inc.",
    "MRK": "Merck & Co., Inc.",
    "TMO": "Thermo Fisher Scientific Inc.",
    "ABT": "Abbott Laboratories",
    "PFE": "Pfizer Inc.",
    "DHR": "Danaher Corporation",
    "AMGN": "Amgen Inc.",
    "ISRG": "Intuitive Surgical, Inc.",
    "BMY": "Bristol-Myers Squibb Company",
    "GILD": "Gilead Sciences, Inc.",
    "VRTX": "Vertex Pharmaceuticals Incorporated",
    "MDT": "Medtronic plc",
    # 7. Industrials, Defense & Aerospace
    "CAT": "Caterpillar Inc.",
    "GE": "General Electric Company",
    "UNP": "Union Pacific Corporation",
    "HON": "Honeywell International Inc.",
    "RTX": "RTX Corporation",
    "BA": "The Boeing Company",
    "DE": "Deere & Company",
    "LMT": "Lockheed Martin Corporation",
    "UPS": "United Parcel Service, Inc.",
    "FDX": "FedEx Corporation",
    # 8. Energy & Natural Resources
    "XOM": "Exxon Mobil Corporation",
    "CVX": "Chevron Corporation",
    "COP": "ConocoPhillips",
    "SLB": "SLB (Schlumberger Limited)",
    "EOG": "EOG Resources, Inc.",
    # 9. Basic Materials & Specialty Chemicals
    "LIN": "Linde plc",
    "SHW": "The Sherwin-Williams Company",
    "FCX": "Freeport-McMoRan Inc.",
    # 10. Utilities & Infrastructure
    "NEE": "NextEra Energy, Inc.",
    "SO": "The Southern Company",
    # 11. Real Estate & Digital Tower Infrastructure
    "PLD": "Prologis, Inc.",
    "AMT": "American Tower Corporation",
    # 12. Market Benchmarks & Macro Regime Proxies
    "SPY": "SPDR S&P 500 ETF Trust",
    "QQQ": "Invesco QQQ Trust Series 1",
    "OPENAI": "OpenAI, Inc. (Pre-IPO Pipeline)",
}
